// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aslam_cv_common/proto/aslam/common/id.proto

#ifndef PROTOBUF_aslam_5fcv_5fcommon_2fproto_2faslam_2fcommon_2fid_2eproto__INCLUDED
#define PROTOBUF_aslam_5fcv_5fcommon_2fproto_2faslam_2fcommon_2fid_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace aslam {
namespace proto {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_aslam_5fcv_5fcommon_2fproto_2faslam_2fcommon_2fid_2eproto();
void protobuf_AssignDesc_aslam_5fcv_5fcommon_2fproto_2faslam_2fcommon_2fid_2eproto();
void protobuf_ShutdownFile_aslam_5fcv_5fcommon_2fproto_2faslam_2fcommon_2fid_2eproto();

class Id;

// ===================================================================

class Id : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:aslam.proto.Id) */ {
 public:
  Id();
  virtual ~Id();

  Id(const Id& from);

  inline Id& operator=(const Id& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Id& default_instance();

  void Swap(Id* other);

  // implements Message ----------------------------------------------

  inline Id* New() const { return New(NULL); }

  Id* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Id& from);
  void MergeFrom(const Id& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Id* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint64 uint = 1;
  int uint_size() const;
  void clear_uint();
  static const int kUintFieldNumber = 1;
  ::google::protobuf::uint64 uint(int index) const;
  void set_uint(int index, ::google::protobuf::uint64 value);
  void add_uint(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      uint() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_uint();

  // @@protoc_insertion_point(class_scope:aslam.proto.Id)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > uint_;
  friend void  protobuf_AddDesc_aslam_5fcv_5fcommon_2fproto_2faslam_2fcommon_2fid_2eproto();
  friend void protobuf_AssignDesc_aslam_5fcv_5fcommon_2fproto_2faslam_2fcommon_2fid_2eproto();
  friend void protobuf_ShutdownFile_aslam_5fcv_5fcommon_2fproto_2faslam_2fcommon_2fid_2eproto();

  void InitAsDefaultInstance();
  static Id* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Id

// repeated uint64 uint = 1;
inline int Id::uint_size() const {
  return uint_.size();
}
inline void Id::clear_uint() {
  uint_.Clear();
}
inline ::google::protobuf::uint64 Id::uint(int index) const {
  // @@protoc_insertion_point(field_get:aslam.proto.Id.uint)
  return uint_.Get(index);
}
inline void Id::set_uint(int index, ::google::protobuf::uint64 value) {
  uint_.Set(index, value);
  // @@protoc_insertion_point(field_set:aslam.proto.Id.uint)
}
inline void Id::add_uint(::google::protobuf::uint64 value) {
  uint_.Add(value);
  // @@protoc_insertion_point(field_add:aslam.proto.Id.uint)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
Id::uint() const {
  // @@protoc_insertion_point(field_list:aslam.proto.Id.uint)
  return uint_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
Id::mutable_uint() {
  // @@protoc_insertion_point(field_mutable_list:aslam.proto.Id.uint)
  return &uint_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace aslam

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_aslam_5fcv_5fcommon_2fproto_2faslam_2fcommon_2fid_2eproto__INCLUDED
